<?php
const COURSES_IBLOCK = 2;
const MATERIALS_IBLOCK = 3;
const NEWS_IBLOCK = 4;
const ROLES_IBLOCK = 5;
const SHEDULES_IBLOCK = 6;
const SPEAKERS_IBLOCK = 7;
const MATERIALS_FILES_IBLOCK = 8;
const POLLS_IBLOCK = 9;
const DEALER_IBLOCK = 10;
const TESTS_IBLOCK = 11;
const TEST_QUESTIONS_IBLOCK = 12;
const CERT_IBLOCK = 13;
const COMPLETIONS_IBLOCK = 14;
const ZOOM_ACCOUNTS_IBLOCK = 17;
const FEEDBACK_POLL_IBLOCK = 19;
const TEST_DRIVE_GROUP_IBLOCK = 32;