name: Update Belgee

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout lms_geely
        uses: actions/checkout@v2

      - name: Checkout lms_belgee
        uses: actions/checkout@v2
        with:
          repository: romannesterenko/lms_belgee
          token: ${{ secrets.PAT_LMS_BELGEE }}
          path: lms_belgee  # Путь к копии репозитория lms_belgee

      - name: Determine changed files
        id: changes
        run: |
          PARENT_COMMIT=$(git log -2 --pretty=format:"%H" | tail -n 1)
          echo "PARENT_COMMIT=$PARENT_COMMIT"
          CHANGED_FILES=$(git diff --name-only $PARENT_COMMIT HEAD)
          echo "CHANGED_FILES=$CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Sync files
        run: |
          echo "Changed files: ${{ env.CHANGED_FILES }}"
          rsync -av --delete --exclude='.git' --exclude='lms_belgee' $GITHUB_WORKSPACE/ lms_belgee/

      - name: Commit and push changes
        run: |
          cd lms_belgee
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automatic update from lms_geely"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_LMS_BELGEE }}

      - name: Развертывание на Belgee
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          echo "$CHANGED_FILES" | tr ' ' '\n' | xargs -I {} rsync -av -e "ssh -i private_key -o StrictHostKeyChecking=no" lms_belgee/{} u520251@u520251.ssh.masterhost.ru:~/ttt/www
          rm private_key


