name: Update Belgee

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout lms_geely
        uses: actions/checkout@v2

      - name: Checkout lms_belgee
        uses: actions/checkout@v2
        with:
          repository: romannesterenko/lms_belgee
          token: ${{ secrets.PAT_LMS_BELGEE }}
          path: lms_belgee  # Путь к копии репозитория lms_belgee

      - name: Sync files
        run: |
          rsync -av --delete --exclude='.git' --exclude='lms_belgee' $GITHUB_WORKSPACE/ lms_belgee/

      - name: Commit and push changes
        run: |
          cd lms_belgee
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automatic update from lms_geely"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_LMS_BELGEE }}

      - name: Развертывание на Belgee
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -av -e "ssh -i private_key -o StrictHostKeyChecking=no" lms_belgee/ u520251@u520251.ssh.masterhost.ru:~/lms.smr-motors.com/www
          rm private_key

      - name: Развертывание на Pangocaready
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_PANGOCAREADY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key_pangocaready
          chmod 600 private_key_pangocaready
          rsync -av -e "ssh -i private_key_pangocaready -o StrictHostKeyChecking=no" lms_belgee/ u2694077@31.31.196.13:~/www/pangocaready.academy
          rm private_key_pangocaready


